base00: "232a2e" # base
base01: "2b3337" # surface0
base02: "374145" # surface1
base03: "4a585c" # surface2
base04: "58686d" # overlay0
base05: "f8f9e8" # text
base06: "adc9bc" # subtext1
base07: "fae6ef" # cherry
base08: "f57f82" # red
base09: "f7a182" # orange
base0A: "f5d098" # yellow
base0B: "cbe3b3" # green
base0C: "b3e3ca" # aqua
base0D: "b2caed" # blue
base0E: "d2bdf3" # purple
base0F: "f3c0e5" # pink