$red = rgb(f57f82)
$orange = rgb(f7a182)
$yellow = rgb(f5d098)
$lime = rgb(dbe6af)
$green = rgb(cbe3b3)
$aqua = rgb(b3e3ca)
$skye = rgb(b3e6db)
$snow = rgb(afd9e6)
$blue = rgb(b2caed)
$purple = rgb(d2bdf3)
$pink = rgb(f3c0e5)
$cherry = rgb(fae6ef)
$text = rgb(f8f9e8)
$subtext1 = rgb(adc9bc)
$subtext0 = rgb(96b4aa)
$overlay2 = rgb(839e9a)
$overlay1 = rgb(6f8788)
$overlay0 = rgb(58686d)
$surface2 = rgb(4a585c)
$surface1 = rgb(374145)
$surface0 = rgb(2b3337)
$base = rgb(232a2e)
$mantle = rgb(1c2225)
$crust = rgb(171c1f)
