[colors.primary]
background = "#232a2e"
foreground = "#f8f9e8"

[colors.cursor]
text = "#232a2e"
cursor = "#f8f9e8"

[colors.selection]
text = "#232a2e"
background = "#f8f9e8"

[colors.normal]
black = "#374145"
red = "#f57f82"
green = "#cbe3b3"
yellow = "#f5d098"
blue = "#b2caed"
magenta = "#d2bdf3"
cyan = "#b3e3ca"
white = "#adc9bc"

[colors.bright]
black = "#4a585c"
red = "#f57f82"
green = "#cbe3b3"
yellow = "#f5d098"
blue = "#b2caed"
magenta = "#d2bdf3"
cyan = "#b3e3ca"
white = "#f8f9e8"
